/*
 * AutoServiceUpdateMode.h
 *
 *  Created on: 2016-2-16
 *      Author: timothy.liao
 */

#ifndef AUTOSERVICEUPDATEMODE_H_
#define AUTOSERVICEUPDATEMODE_H_

enum AutoServiceUpdateMode{
    E_SAU_OFF = 0,
    E_SAU_NITVERSION,
    E_SAU_NITSDT,
    E_SAU_NITSDTBAT, 
    E_SAU_NITSDTSDTOTHER,
    E_SAU_NITSDTSDTOTHERBAT,
    E_SAU_NITSDTSDTOTHER_NOTADDSERVICE,
    E_SAU_NITSDTSDTOTHER_NOTADDSERVICE_NOTUPDATESERVICENAME
};

#endif /* AUTOSERVICEUPDATEMODE_H_ */
