#ifndef  FILELISTSCANPUBLICTYPE_H_
#define FILELISTSCANPUBLICTYPE_H_


#define MAX_FILE_DIR_LEN  512

#define MAX_FILE_NAME_LEN 256

#define MAX_FILE_MOUNT_PATH 64

#endif //FILELISTSCANPUBLICTYPE_H_ 
