/*
 * AudioFormat.h
 *
 *  Created on: 2015-4-8
 *      Author: timothy.liao
 */

#ifndef AUDIOFORMAT_H_
#define AUDIOFORMAT_H_


enum AudioFormat{
    E_AUDIOFORMAT_NONE = 0,
    E_AUDIOFORMAT_MPEG1,
    E_AUDIOFORMAT_MPEG2,
    E_AUDIOFORMAT_AC3,
    E_AUDIOFORMAT_AC3PLUS,
    E_AUDIOFORMAT_AAC,
    E_AUDIOFORMAT_MP3,
    E_AUDIOFORMAT_WMA,
    E_AUDIOFORMAT_XPCM,
    E_AUDIOFORMAT_DTS,
    E_AUDIOFORMAT_MS10DDT,
    E_AUDIOFORMAT_MS10DDC,
    E_AUDIOFORMAT_WMA_PRO,
    E_AUDIOFORMAT_FLAC,
    E_AUDIOFORMAT_AVS,
    E_AUDIOFORMAT_MPEG4,
    E_AUDIOFORMAT_MAX
};



#endif /* AUDIOFORMAT_H_ */
