/*
 * AudioChannel.h
 *
 *  Created on: 2015-4-8
 *      Author: timothy.liao
 */

#ifndef AUDIOCHANNEL_H_
#define AUDIOCHANNEL_H_


enum AudioChannel{
    E_AUDIOCHANNEL_MONO = 0,
    E_AUDIOCHANNEL_DUALMONO,
    E_AUDIOCHANNEL_2CHANNEL,
    E_AUDIOCHANNEL_2CHANNEL_SURROUND,
    E_AUDIOCHANNEL_MULTICHANNEL5_1,
    E_AUDIOCHANNEL_MULTICHANNEL7_1,
    E_AUDIOCHANNEL_RESERVE1,
    E_AUDIOCHANNEL_RESERVE2,

    E_AUDIOCHANNEL_DUALMONO_LEFT = 0x40,
    E_AUDIOCHANNEL_DUALMONO_RIGHT = 0x41

};



#endif /* AUDIOCHANNEL_H_ */
