/*
 * UpgradeCommand.h
 *
 *  Created on: 2015-8-17
 *      Author: linc
 */

#ifndef UPGRADECOMMAND_H_
#define UPGRADECOMMAND_H_

typedef enum
{
	//Uprade
	E_UPGRADE_COMMAND_STB_SEND_UPGRADE_COMMAND = 0x20,
	E_UPGRADE_COMMAND_PC_SEND_ACK,
	E_UPGRADE_COMMAND_STB_REQ_SN,
	E_UPGRADE_COMMAND_PC_SEND_SN,
	E_UPGRADE_COMMAND_STB_REQ_HDCP,
	E_UPGRADE_COMMAND_PC_SEND_HDCP,
	E_UPGRADE_COMMAND_STB_REQ_MAC,
	E_UPGRADE_COMMAND_PC_SEND_MAC,//0x27
	E_UPGRADE_COMMAND_STB_REQ_PEF,
	E_UPGRADE_COMMAND_PC_SEND_PEF,
	
	E_UPGRADE_COMMAND_STB_SEND_WAIT_SEND_UPGRADE_RESULT,
	E_UPGRADE_COMMAND_PC_SEND_REQ_UPGRADE_RESULT,
	E_UPGRADE_COMMAND_STB_SEND_UPGRADE_RESULT,
	E_UPGRADE_COMMAND_PC_SEND_UPGRADE_RESULT,//0x2D

	E_UPGRADE_COMMAND_STB_SEND_INSERT_DB,
	E_UPGRADE_COMMAND_PC_SEND_INSERT_RESULT,//0x2F
	//Verify
	E_UPGRADE_COMMAND_STB_SEND_WAIT_VERIFY,
	E_UPGRADE_COMMAND_PC_SEND_VERIFY_COMMNAD,
	E_UPGRADE_COMMAND_STB_SEND_VERIFY_DATA,
	E_UPGRADE_COMMAND_PC_SEND_VERIFY_RESULT,//0x33

	E_UPGRADE_COMMAND_STB_SEND_VERIFY_FINISHED,
	E_UPGRADE_COMMAND_PC_SEND_VERIFY_FINISHED,
	
	//Repair
	E_UPGRADE_COMMAND_PC_SEND_REQ_RETURNFILE_AGAIN,
	E_UPGRADE_COMMAND_PC_SEND_ERASE_COMMNAD,
	
	E_UPGRADE_COMMAND_STB_SEND_ERASE_RESULT,//0x38
	E_UPGRADE_COMMAND_STB_SEND_CHIPID_ERROR,
	E_UPGRADE_COMMAND_PC_REQ_UPGRADE_STATUS,
	E_UPGRADE_COMMAND_STB_SEND_UPGRADE_STATUS,

	//Conax Personalization
	E_UPGRADE_COMMAND_STB_SEND_PERSONALIZE_COMMAND,
	E_UPGRADE_COMMAND_PC_SEND_ENCRYT_KEY,
	E_UPGRADE_COMMAND_STB_SEND_ENCRYT_RESULT,
	E_UPGRADE_COMMAND_PC_SEND_VSCDATA_LENGTH,
	E_UPGRADE_COMMAND_STB_REQUEST_VSCDATA,
	E_UPGRADE_COMMAND_PC_SEND_VSCDATA,
	E_UPGRADE_COMMAND_STB_RECV_VSCDATA,
	E_UPGRADE_COMMAND_PC_REQ_PERSONALIZE_RESULT,
	E_UPGRADE_COMMAND_STB_SEND_PERSONALIZE_RESULT,//0x44

	E_UPGRADE_COMMAND_STB_SEND_PHY_INTERFACE_RESULT,
	E_UPGRADE_COMMAND_PC_RES_PHY_INTERFACE_RESULT,//0x46

	//Irdeto IFCP SET
	E_UPGRADE_COMMAND_STB_REQ_IFCP_SIZE,//0x47
	E_UPGRADE_COMMAND_PC_SEND_IFCP_SIZE,
	E_UPGRADE_COMMAND_STB_REQ_IFCP,
	E_UPGRADE_COMMAND_PC_SEND_IFCP,//0x4A
	E_UPGRADE_COMMAND_STB_REQ_IFCP_MAX = 0x6A,
	E_UPGRADE_COMMAND_PC_SEND_IFCP_MAX,//0x6B
	E_UPGRADE_COMMAND_STB_SEND_IFCP_RESULT,//0x6C
	E_UPGRADE_COMMAND_PC_SEND_IFCP_RESULT,//0x6D

	E_UPGRADE_COMMAND_END
}UPGRADE_COMMAND;

typedef enum
{
	WAIT_UPGRADE_DATA = 0,
	UPGRADE_FINISHED,
	WAIT_SEND_RETURNFILE,
	WAIT_DB_RESULT,
	WAIT_VERIFY,
	CHIPID_ERROR,
	WAIT_COMMAND,
	WAIT_CONAX_PERSONALIZE,
	WAIT_IRDETO_IFCP,
	MAX_STATUS
}UPGRADE_STATUS;

#endif /* UPGRADECOMMAND_H_ */
