/*
 * PlayError.h
 *
 *  Created on: 2015-6-23
 *      Author: linc
 */

#ifndef PLAYERROR_H_
#define PLAYERROR_H_

enum PlayError{
	E_PLAY_SUCCESS = 0,
	E_PLAY_ERROR_PARAM_ERROR,
	E_PLAY_ERROR_NO_SPACE,
	E_PLAY_ERROR_NO_DEVICE,
	E_PLAY_ERROR_DEVICE_NOT_READY,
	E_PLAY_ERROR_RECORD_STARTED,
	E_PLAY_ERROR_PLAYBACK_STARTED,
	E_PLAY_ERROR_TIMESHIFT_STARTED,
	E_PLAY_ERROR_ADIOPEN_FAIL,
	E_PLAY_ERROR_READ_RECINFO_FAIL,
	E_PLAY_ERROR_GET_STREAM_INFO_FAIL,//10
	E_PLAY_ERROR_ADISTART_FAIL,
	E_PLAY_ERROR_GET_SERVICE_INFO_FAIL,
	E_PLAY_ERROR_GET_FILE_PATH_FAIL,
	E_PLAY_ERROR_GET_ENCRYPT_INFO_FAIL,
	E_PLAY_ERROR_ADI_SET_STREAM_FAIL,//15
	E_PLAY_ERROR_ADICLOSE_FAIL,
	E_PLAY_ERROR_ADISTOP_FAIL,
	E_PLAY_ERROR_ADIPAUSE_FAIL,
	E_PLAY_ERROR_NOT_START,
	E_PLAY_ERROR_LOCKED,//20
	E_PLAY_ERROR_PLAY_SUBTITLE_FAIL,
	E_PLAY_ERROR_MAC_ERROR,
	E_PLAY_ERROR_FP_NOT_FREE,
	E_PLAY_ERROR_READ_FP_FAIL,
	E_PLAY_ERROR_OSD_NOT_FREE,//25
	E_PLAY_ERROR_READ_OSD_FAIL,
	E_PLAY_ERROR_URI_NOT_FREE,
	E_PLAY_ERROR_READ_URI_FAIL,
	E_PLAY_ERROR_SUBMIT_DATA_FAIL,
	E_PLAY_ERROR_MOVIE_STARTED,//30
    E_PLAY_ERROR_EXPIRED,
    E_PLAY_ERROR_TRCKMODE_ERROR,
    E_PLAY_ERROR_ECM_CHECK_FAIL,
    E_PLAY_ERROR_TSHIFT_DURATION_NOT_ENOUGH,
    E_PLAY_ERROR_ECMPOS_NOT_FREE,
    E_PLAY_ERROR_READ_ECMPOS_FAIL,
	E_PLAY_ERROR_MAX
};


#endif /* PLAYERROR_H_ */
