/*
 * RecordError.h
 *
 *  Created on: 2015-6-23
 *      Author: cl
 */

#ifndef RECORDERROR_H_
#define RECORDERROR_H_

enum RecordError{
	E_RECERROR_SUCCESS = 0,
	E_RECERROR_PARAM_ERROR,
	E_RECERROR_NO_SPACE,
	E_RECERROR_NO_DEVICE,
	E_RECERROR_DEVICE_NOT_READY,
	E_RECERROR_RECORD_STARTED,//5
	E_RECERROR_PLAYBACK_STARTED,
	E_RECERROR_TIMESHIFT_STARTED,
	E_RECERROR_ADIOPEN_FAIL,
	E_RECERROR_GET_FILE_NAME_FAIL,
	E_RECERROR_GET_FILE_PATH_FAIL,
	E_RECERROR_REQUEST_PMT_FAIL,
	E_RECERROR_GET_STREAM_INFO_FAIL,//12
	E_RECERROR_GET_ENCRYPT_INFO_FAIL,
	E_RECERROR_ADISTART_FAIL,
	E_RECERROR_GET_SERVICE_INFO_FAIL,
	E_RECERROR_CONSTRUCT_DATA_FAIL,
	E_RECERROR_SAVE_REC_INFO_FAIL,
	E_RECERROR_ADICLOSE_FAIL,
	E_RECERROR_ADISTOP_FAIL,
	E_RECERROR_NOT_START,
	E_RECERROR_STARTCA_FAIL,//21
	E_RECERROR_CA_PG_LOCK,
	E_RECERROR_FP_NOT_FREE,
	E_RECERROR_OSD_NOT_FREE,
	E_RECERROR_URI_NOT_FREE,
	E_RECERROR_GET_URI_FAIL,//26
    E_RECERROR_ECMPOS_NOT_FREE,
	E_RECERROR_MAX
};


#endif /* RECORDERROR_H_ */
